import{a as b,S,i as L}from"./assets/vendor-951421c8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const $=document.querySelector(".input-search"),u=document.querySelector(".form-search"),d=document.querySelector(".gallery");document.querySelector(".button-submit");const i=document.querySelector(".button-load"),w=document.querySelector(".loader"),x=40;let c=1,l=0,p="";w.hidden=!0;i.hidden=!0;u.addEventListener("submit",async r=>{r.preventDefault(),c=1,d.innerHTML="";try{const{total:t,hits:n}=await m(c);l=Math.ceil(t/n.length),f(n),i.hidden=l<=1}catch{h("Sorry, there was an error loading images.")}});i.addEventListener("click",async r=>{r.preventDefault(),c++;try{const{hits:t}=await m(c,p);f(t)}catch{h("Sorry, there was an error loading more images."),i.hidden=!0}});async function m(r,t=$.value){const n="42111796-9c286351ad531542ab3bfb8be";return p=t,(await b.get(`https://pixabay.com/api/?key=${n}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${x}&page=${r}`)).data}function f(r){const t=r.map(({webformatURL:a,tags:e,likes:o,views:s,comments:g,downloads:y})=>`
        <li class="gallery-item"><a href="${a}">
        <img class="gallery-image" src="${a}" alt="${e}"></a>
        <p>Likes: ${o}</p>
        <p>Views: ${s}</p>
        <p>Comments: ${g}</p>
        <p>Downloads: ${y}</p>
        </li>`).join("");d.insertAdjacentHTML("beforeend",t);const n=new S(".gallery a",{captions:!0,captionSelector:"img",captionsData:"alt",captionPosition:"bottom",animation:250});n.on("show.simplelightbox"),n.refresh(),u.reset()}function h(r){L.error({message:r,class:"izi-toast",messageColor:"#fafafb",messageSize:"16px",backgroundColor:"#ef4040",maxWidth:"432px",position:"topRight"})}
//# sourceMappingURL=commonHelpers.js.map
